name = "Ages Of Siege"
author = "stamperl"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41e31da446149d5d6ea3a86be8663a55890ccde6f658244e75357bdfe4e6ca20"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
