name = "Ages Of Siege"
author = "stamperl"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3cda93901a4ca770c79cdef98679bdbc346c80f6cf2a764209633a38e2a8f1c"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
