name = "Ages Of Siege"
author = "stamperl"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ef2636ba93c78e8ea188fc4f294e56b1f4a88901101e758791721af7d52b0e9"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
